name Android APK

on
  workflow_dispatch

jobs
  build
    runs-on ubuntu-24.04
    steps
      - uses actionscheckout@v4

      - name System deps
        run 
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip python3-venv 
            autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev 
            libtinfo6 cmake libffi-dev libssl-dev automake autopoint gettext
          curl httpssh.rustup.rs -sSf  sh -y
          echo $HOME.cargobin  $GITHUB_PATH

      - name Python venv + buildozer
        run 
          python3 -m venv venv
          . venvbinactivate
          pip install --upgrade pip
          pip install buildozer cython==0.29.34

      - name Build APK
        run 
          . venvbinactivate
          buildozer -v android debug

      - name Upload APK
        uses actionsupload-artifact@v4
        with
          name apk
          path bin.apk
